Updated tramsform_prox_AoAs_to_blade_AoAs_kwargs argument in __init__.py.
Updated tramsform_prox_AoAs_to_blade_AoAs_kwargs argument to be a dict and not nonetype because that causes errors with later code. The following error is now prevented

TypeError: bladesight.btt.aoa.transform_prox_AoAs_to_blade_AoAs() argument after ** must be a mapping, not NoneType